### ISSUE TITLE
Suggest separating the vocabulary files from the model file

### ISSUE THREAD

**Issue by netxiao** [OpenNMT/OpenNMT#148]
In my practice, there is no perfect clean data in real world, corpus is always exists some unclean data, a few wrong words will exist in the vocabulary, for example:
```
<blank> 1
<unk> 2
<s> 3
</s> 4
a 5
` 6
^ 7
c 8
~ 9
errar_aa 10
```
after the completion of the training, **errar_aa** will show translation errors as:
`what is ascii errar_aa  complete  errar_aa  including hex`

if I want to fix this type of problem, I can only retrain once, but it is very difficult to check tens of thousands of vocabularies.

I think that vocabulary files is just an index array, if it can be separated independently,modify the index table is very convenient and easy.

**Comment by guillaumekln** [comment]
Vocabularies are voluntarily bundled in the model to avoid user errors.

How much data do you use? Supposing unclean data are by an order of magnitude less frequent than clean data, the model will most likely not predict these words. Otherwise, it is important to make sure that your target data are as clean as possible (maybe by using an automated process with some heuristics to discard unclean sequences).

**Comment by netxiao** [comment]
I have used a lot of methods and steps to clean the data from web (18 million),  but few wrong word still exist in sentences, so I think that automatically generate vocabularies will make some mistakes are inevitable.  

When I find that there are vocabulary errors in translation result,  go to modify the vocabulary, and then re-training again, but it's need too much time. If  can direct modify the vocabulary file,  just replace the wrong vocabulary can be fixed.

so I think a practical translation system, manual maintenance vocabulary is important and reduce the cost of time.
