### ISSUE TITLE
Can this model used for summarization? 

### ISSUE THREAD

**Issue by maplewizard** [OpenNMT/OpenNMT#16]
Can this model used for summarization? Is there anything I should modify if I want to use this model in summarization tasks?

**Comment by da03** [comment]
I think so. Summarization is a special case of machine translation, where the source language and the target language are the same.

**Comment by maplewizard** [comment]
@da03  Have you ever tried a summarization task? Is there anything different from translation tasks?

**Comment by da03** [comment]
It should be basically the same, but I think in this case the `-replace_unk` option would be helpful. (http://opennmt.net//Guide/#translating-unk-words). Besides, since the target and source language are the same, their vocabularies may be shared and their word vectors may be tied. However, from our experience on the CNN/Daily Mail dataset (we used that for summarization), that does not help, and the current code does not support doing that.

References:
1. A work applying seq2seq to summarization task: Nallapati et al. Abstractive Text Summarization using Sequence-to-sequence RNNs and Beyond. arxiv:1602.06023
2. A summarization dataset: https://github.com/harvardnlp/sent-summary

**Comment by da03** [comment]
BTW, we have posted some results on this page, including a summarization result on Gigaword: http://opennmt.net//Models/

**Comment by jroakes** [comment]
@da03:  I may be missing something but I am getting "access denied" for the summarization files listed on your link.

**Comment by maplewizard** [comment]
I encountered the same problem.

**Comment by da03** [comment]
Sorry, the model might be still uploading. Will fix that soon.

**Comment by da03** [comment]
Fixed now.

**Comment by jroakes** [comment]
Perfect.  Thanks.  Was the same code used for the summarization or is there another repo?

**Comment by da03** [comment]
It's the same code.

**Comment by DA1234k** [comment]
i have take few amount of data after translation it will be give unk sentences how to resolve problem in OpenNMT.
