### ISSUE TITLE
Stuck on "preparing memory optimization"

### ISSUE THREAD

**Issue by xplkqlkcassia** [OpenNMT/OpenNMT#22]
```
Preparing memory optimization...	
 * sharing 63% of output/gradInput tensors memory between clones
```

MacOS v.10.12.1 (Sierra) 
MacBook Pro (Mid 2010)
Processor: 2.4 GHz Intel Core 2 Duo
Memory: 4 GB 1067 MHz DDR3
Graphics: NVIDIA GeForce 320M 256 MB

No changes made to any of the training data. 

How do I work around this? Is it a hardware config problem or a bug?

**Comment by jroakes** [comment]
How long have you waited?  It can take some time.

**Comment by xplkqlkcassia** [comment]
How long usually?

**Comment by guillaumekln** [comment]
It should not take very long actually.

I suppose you are running on the CPU. Can you check that your memory is not swapping? 4GB is fairly low for this type of application.

**Comment by guillaumekln** [comment]
If you can read this message:

```
 * sharing 63% of output/gradInput tensors memory between clones
```

It means that the memory optimization step has already happened and the training has started (I will add a message to be more explicit). The first few iterations take longer because the network needs to be cloned several times to match the sequence length. It is quite costly.

Additionally, your memory is fairly small. You should check that your system is not swapping.
