### ISSUE TITLE
Documentation for given version

### ISSUE THREAD

**Issue by Gldkslfmsd** [OpenNMT/OpenNMT#381]
Hello,

I have a suspicion that some of my issues are caused by using the web documentation on http://opennmt.net/OpenNMT/options/train/ , which doesn't agree with the latest release I'm using. Is it possible that some options in documentation are not available there? If yes, then I suggest a new feature: allow browsing the web documentation for given release. (I know I can use my own doc server, but it's inconvenient and causes issues before a user figures it out.)

**Comment by guillaumekln** [comment]
The web documentation targets the master version of the repository. Unfortunately, the documentation system we use does not support multiple versions.

If you are not using the master version of OpenNMT, you can find the complete documentation as Markdown files in the `docs/` directory.

**Comment by Gldkslfmsd** [comment]
OK. The docs directory is nice. You can at least add a link to multiple versions of it. I think other users would appreciate it. Master is changing too fast, longer projects require consistency...

**Comment by jsenellart** [comment]
yes - you are right, we will try to find a way to do that.

**Comment by Gldkslfmsd** [comment]
```
train.lua: option -validation_metric is not in accepted values: perplexity, loss, bleu, dlratio
Try 'train.lua -h' for more information, or visit the online documentation at http://opennmt.net/OpenNMT/.
```
When you do it, don't forget to update the link in this message.

**Comment by jsenellart** [comment]
experimental multi-version doc deployment using mkultra (https://github.com/jimporter/mkultra)

process is the following:
-	Regular gh-deploy sur le master => this reset all deployed version!
-	checkout version: `git checkout vx.y.z`
-	add in mkdocs.yml the navigation code (ultimately this should be integrated in the branch)
```
extra_javascript :
[...]
- http://opennmt.net/OpenNMT/js/version-select.js
- https://code.jquery.com/jquery-3.2.1.slim.min.js
- https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js
extra_css:                                                                                                                              
[...]
  - https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css                                                 
```

-	deploy with `mkultra deploy -p x.y.z` (/!\ the version has to be numeric since it is used for the selector setting - or modify `version-select.js`)
-	you can list and managed deployed version with `mkultra list`, `delete`...
