### ISSUE TITLE
How to feed word features during model inference

### ISSUE THREAD

**Issue by getao** [OpenNMT/OpenNMT#497]
Hi, I've seen that word features can be fed to model with the "|" indicator when training a model. I wonder if the features should be fed in the same way during inference.

Moreover, I wonder how I can use the word features in other ways than 'sum' or 'concat'. For instance, I want to use an RNN or CNN to encode the character information and concat it to word embedding.

Thanks

**Comment by guillaumekln** [comment]
Hello,

* The inference data should be formatted the same way otherwise an error will be raised.
* Features are only implemented as discrete labels mapped into an embedding space.

*If you are interested in character aware encoding, you should take a look at [OpenNMT-tf](https://github.com/OpenNMT/OpenNMT-tf). There is an [example model](https://github.com/OpenNMT/OpenNMT-tf/blob/master/config/models/seq_tagger.py#L8) that concatenates word embeddings and character representations produced by a CNN.*

**Comment by getao** [comment]
Thank you very much. It is exactly what I want.
