### ISSUE TITLE
-train_from option doesn't support -model_type lm????

### ISSUE THREAD

**Issue by getao** [OpenNMT/OpenNMT#499]
Hello. I trained a language model using OpenNMT. I want to train from a previous checkpoint but I always got the following error:

torch/install/bin/lua: train.lua:272: attempt to index field 'tgt' (a nil value)

I wonder if OpenNMT supports the train_from option for language model training.

Another question: if I want to use the trained language model to to help decoding during inference for a seq2seq model, does the langauge model's word dictionary need to be the same with the seq2seq target dictionary?

**Comment by jsenellart** [comment]
Hello @getao - I am not sure the `train_from` was tested for LM - I am running a sanity test and will come back to you.

For your second question - yes, it does need to be identical with the current implementation, it is not a hard requirement and we could change that but is it really a normal use case for you?

**Comment by getao** [comment]
Hi, @jsenellart . Thank you for your answer. For the second question, I tried to find a way to output n-best predictions with their pred scores for re-ranking with a language model but didn't find how to do that except through stdout. That's why I want to decode with a language model during inference.

But I think it is OK for me because I can re-train a language model with the same dictionary with that used for my seq2seq model.

Thank you very much.

**Comment by balbertalli** [comment]
I ran into the same issue the other day. These lines in the loadModel function of train.lua seem to be the culprit:

`elseif checkpoint.dicts.src.words:size() ~= dicts.src.words:size() or checkpoint.dicts.tgt.words:size() ~= dicts.tgt.words:size() then
    _G.logger:warning('Dictionary size changed, you may need to activate -update_vocab option')`

This gets run no matter what model you are using, and obviously there are no target words if you're using a language model.

Since the faulty elseif line is there just to log a warning if your dictionary size has changed, a quick hack is to just comment those two lines out (if you're using the same dictionary!)

**Comment by getao** [comment]
@balbertalli  Thank you for your solution. I'll try later.
