### ISSUE TITLE
Indicate progress while training

### ISSUE THREAD

**Issue by akuckartz** [OpenNMT/OpenNMT#75]
After "Start training..." it usually takes a long time until there is the next output. Please add some indication that there is progress.

**Comment by guillaumekln** [comment]
You can change the log frequency with the `-report_every` option. By default, it logs something every 50 iterations which can take some time to reach, especially for CPU training.

Note that the first few iterations are longer by design as the network has to compensate for sequence length it has not seen before.

**Comment by akuckartz** [comment]
@guillaumekln Thanks for that info ! Maybe that information should be used to modify http://opennmt.net/Guide/#step-2-train-the-model ?

(The first 50 interations took about 1 hour on the machine I am currently using...)

**Comment by guillaumekln** [comment]
The quickstart guide only showcases the most basic training workflow with the minimal options. Other translation options are nicely summarized in `th translate.lua -h`.
